FROM arm32v7/node:lts-stretch
LABEL maintainer="Maxime Signoret"

RUN npm install pm2 -g

WORKDIR /usr/app

RUN mkdir data/

VOLUME data/

COPY src src/
COPY public public/
COPY package.json .
COPY pm2.json .

ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install --production

CMD [ "pm2-runtime", "start", "pm2.json" ]